### ISSUE TITLE
Some Titles with titlekeys aren't flagged properly

### ISSUE THREAD

**Issue by metaboss** [d0k3/eshop-analysis#2]
There are a few titles that have keys but are flagged as titlekey_known=FALSE in the result csv.

I think this is because of a minor mismatch in the product code.

Examples:

CTR-**N**-QBFA - Pokemon Yellow  misses match with CTR-**P**-QBFA titlekey
CTR-**N**-BYHP - YO-KAI Watch Fleshy Souls misses match with CTR-**P**-BYHP titlekey
CTR-**P**-AXXE - Project X Zone misses match with CTR-**N**-AXXE titlekey

matching on only the last 4 of the product code or title id (when available) would probably resolve this.

**Comment by d0k3** [comment]
Alright, thanks. __-N-__ is for a digital only release, __-P-__ is for a retail cartridge (+ digital) release. ~~Basically all entries in the titlekeys db should have __-N-__ cause a retail cartridge obviously does not have a titlekey. Giving the titlekeys page a quick glance, that is obviously not the case.~~ I'll do a workaround on my side, it may also make sense to open an issue on that titlekey site (however that may work).

A word of warning, though (and I know, this info needs to go to the titlekeys site, not here). If an entry in there has __-P-__, especially one that doesn't match the __-N-__ from the eshop, it may have been created from a cart -> CIA conversion, and _it will have a wrong titlekey then_. This is only prevented on the latest release of GM9, all older versions and alternative tools can't discern bad titlekeys from good. So, these titlekeys at least need testing.

Something that you could check for me: Do the title IDs match then? You need the most recent version of the script (read the readme), not the release one.

**Comment by d0k3** [comment]
Okay, I tried it, that's a whopping 7 titles with mismatched -N- or -P-. Most likely a mixup on the side of the titlekey db, cause it's very doubtful there is wrong metadata on Nintendo's own eshops.

Example: Pokemon Yellow most likely never had a 3DS compatible cart release, right? Yet, it has a -P- inside of it's product code on the titlekey db.

It really is better to fix this on the side of the titlekey db, cause that also has to work with the eshop metadata. So.... can we have words with someone who knows someone who runs the titlekey db or something? Please?

**Comment by d0k3** [comment]
Okay, as the titlekey site does no more exist, we can close this.
