### ISSUE TITLE
Idiomatic Python

### ISSUE THREAD

**Issue by Nemris** [d0k3/eshop-analysis#3]
Good day to you!

I've noticed that you seem to have written this program partly as an exercise in learning Python.

If so - are you interested in PRs that introduce a more idiomatic approach to your code, seeing how your current program is - obviously without offense intended - more C-like than Pythonic?

**Comment by d0k3** [comment]
Improvements to this script are welcome. Small commits preferred. Before you start, wait a day or two. I need to commit my most recent changes. And, you are right, this was one of the first Python scripts I wrote.

**Comment by d0k3** [comment]
Alright, I checked, and actually everything was up to date earlier. So, you can start, and I will close this for now as your question is answered. Just one small request: one big pull request is prefered over multiple ones. These days, I may not be able to follow up for several days.

**Comment by Nemris** [comment]
Perfect - I'll make sure to leave notes explaining the single commits as well. Might take a bit as I have a lot on my plate as of now, however.

**Comment by Nemris** [comment]
It's vaguely late, but work on the refactoring has begun. You can check it out at [Nemris/eshop-analysis](https://github.com/Nemris/eshop-analysis), on the `refactor` branch.

**Comment by Nemris** [comment]
For the record, the current "key site" logic would work only with an archived version of that site - which counts roughly 1k titles less than the latest source. I'll likely change it to handle the new source.
